# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dz_AlexeyMalkov' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod "PromiseKit"
  # Pods for dz_AlexeyMalkov

end
